import React from 'react';
import Head from 'next/head';
import { FunctionComponent } from 'react';
interface MainLayoutProps {
  title: string;
}
const MainLayout: FunctionComponent<MainLayoutProps> = (props) => {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.children}
    </>
  );
};
export default MainLayout;
