import React from 'react';
import Head from 'next/head';
import { FunctionComponent } from 'react';
import styles from './MainLayout.module.scss';
interface MainLayoutProps {
  title: string;
}
const MainLayout: FunctionComponent<MainLayoutProps> = (props) => {
  const [left, ...mainContent] = React.Children.toArray(props.children);

  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={'flex flex-row h-screen'}>
        <div className={styles.sidenav + ' md:w-1/6 sm:w-1/12'}>{left}</div>
        <div className={'grow'}>{mainContent}</div>
      </div>
    </>
  );
};
export default MainLayout;
