import React from 'react';
import Head from 'next/head';
import { FunctionComponent } from 'react';
import styles from './MainLayout.module.scss';
import SideNav from '@client/components/layouts/SideNav/SideNav';

interface MainLayoutProps {
  title: string;
}
const MainLayout: FunctionComponent<MainLayoutProps> = (props) => {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={'flex flex-row h-screen'}>
        <div className={'md:w-1/6 sm:w-1/12'}>
          <SideNav />
        </div>
        <div className={'grow'}>{props.children}</div>
      </div>
    </>
  );
};
export default MainLayout;
